"""
    Battery Archive API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.tests_api import TestsApi  # noqa: E501


class TestTestsApi(unittest.TestCase):
    """TestsApi unit test stubs"""

    def setUp(self):
        self.api = TestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_test(self):
        """Test case for create_test

        Create a test for cellId  # noqa: E501
        """
        pass

    def test_show_all_tests_for_cell_id(self):
        """Test case for show_all_tests_for_cell_id

        Info for a specific cell  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
