"""
    Battery Archive API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.cells_api import CellsApi  # noqa: E501


class TestCellsApi(unittest.TestCase):
    """CellsApi unit test stubs"""

    def setUp(self):
        self.api = CellsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cells(self):
        """Test case for create_cells

        Create a cell  # noqa: E501
        """
        pass

    def test_list_cells(self):
        """Test case for list_cells

        List all cells  # noqa: E501
        """
        pass

    def test_show_cell_by_id(self):
        """Test case for show_cell_by_id

        Info for a specific cell  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
