"""
    Battery Archive API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cell import Cell
globals()['Cell'] = Cell
from openapi_client.model.cells import Cells


class TestCells(unittest.TestCase):
    """Cells unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCells(self):
        """Test Cells"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Cells()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
