"""
    Battery Archive API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.cells_api import CellsApi  # noqa: E501


class TestCellsApi(unittest.TestCase):
    """CellsApi unit test stubs"""

    def setUp(self):
        self.api = CellsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cells(self):
        """Test case for get_cells

        Fetches all Cells  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
